//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialShort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialShort()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public long ID { get; set; }
        public string NameMaterial { get; set; }
        public Nullable<long> IdTypeOfMaterial { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<long> IdTypeOfEdinica { get; set; }
        public Nullable<int> CountOnSklad { get; set; }
        public Nullable<int> MinOstatok { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual TypeOfEdinica TypeOfEdinica { get; set; }
        public virtual TypeOfMaterial TypeOfMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
