//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public long ID { get; set; }
        public Nullable<long> IDOfProduct { get; set; }
        public Nullable<long> IDOfMaterial { get; set; }
        public Nullable<int> NeseccaryCount { get; set; }
    
        public virtual MaterialShort MaterialShort { get; set; }
        public virtual Products Products { get; set; }
    }
}
