//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        public long IDView { get; set; }
        public Nullable<long> IDTypeProduct { get; set; }
        public string NameProduct { get; set; }
        public Nullable<int> Article { get; set; }
        public Nullable<int> CountTypeMaterial { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MinPriceAgent { get; set; }
        public string Logo { get; set; }
    
        public virtual TypeOfProduct TypeOfProduct { get; set; }
    }
}
